# Generated by Django 2.1.7 on 2019-10-17 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanTalkRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DanTalkRoom_ID', models.CharField(max_length=10)),
                ('DanTalkRoom_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friend_ID', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DanTalk_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('DanTalk_PW', models.CharField(blank=True, max_length=50, null=True)),
                ('DanTalk_Birth', models.CharField(blank=True, max_length=8, null=True)),
                ('DanTalk_Email', models.CharField(blank=True, max_length=50, null=True)),
                ('DanTalk_Gender', models.CharField(blank=True, max_length=2, null=True)),
                ('DanTalk_PersonalAgree', models.CharField(blank=True, max_length=2, null=True)),
                ('rank', models.CharField(choices=[('1', '관리자'), ('2', '사용자')], default='1', max_length=3)),
                ('DanTalk_SignUpDate', models.DateField(blank=True, null=True, verbose_name='회원가입 날짜')),
                ('DanTalk_LastDate', models.DateField(blank=True, null=True, verbose_name='마지막 접속 시간')),
                ('DanTalk_ClientAddress', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='friendlist',
            name='Have_Friend_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DanTalkMain.User'),
        ),
    ]
