# Generated by Django 2.1.7 on 2019-10-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanTalkMain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dantalkroom',
            name='DanTalkRoom_UsrList',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dantalkroom',
            name='DanTalkRoom_ID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dantalkroom',
            name='DanTalkRoom_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
