# Generated by Django 2.1.7 on 2019-10-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanTalkMain', '0002_auto_20191017_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DanTalk_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
