# Generated by Django 2.1.7 on 2019-10-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanTalkMain', '0003_user_dantalk_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='DanTalk_PersonalAgree',
            field=models.CharField(blank=True, default='1', max_length=2, null=True),
        ),
    ]
