# Generated by Django 2.1.7 on 2019-10-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanTalkMain', '0004_auto_20191017_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('1', '관리자'), ('2', '사용자')], default='2', max_length=3),
        ),
    ]
